version: '3.8'
services:
    mongo:
        image: mongo:7.0
        container_name: smarttraffic-mongo
        restart: always
        ports:
          - "27017:27017"
        volumes:
          - mongo-data:/data/db #variable_name:path_inside_container
    server:
        build: ./server
        container_name: smarttraffic-server
        restart: always
        ports:
          - "5000:5000"
        env_file:
          - ./server/.env
        environment:
          - PORT=5000
          - MONGO_URI=mongodb://mongo:27017/smart_traffic
          - JWT_SECRET=docker_production_secret
        depends_on:
          - mongo

    client:
      build: ./client
      container_name: smarttraffic-client
      restart: always
      ports:
          - "80:80"
      depends_on:
          - server


volumes:
    mongo-data: